volumes:
  db_data:
    name: inception_db_data
  wp_data:
    name: inception_wp_data

networks:
  inception:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    image: mariadb-inceprion
    build:
      context: ./requirements/mariadb/
      args:
        DEBIAN_TAG: ${DEBIAN_TAG}
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    networks: 
      - inception
    restart: always
#    healthcheck:
#      test: ["CMD-SHELL", "mariadb-admin ping -uroot --password=$$(cat ${MYSQL_ROOT_PASSWORD}) || exit 1"]
#      interval: 5s
#      timeout: 3s
#      retries: 10

  wordpress:
    container_name: wordpress
    image: wordpress-inceprion
    build:
      context: ./requirements/wordpress/
      args:
        DEBIAN_TAG: ${DEBIAN_TAG}
          #depends_on:
      #mariadb:
        #        condition: service_healthy
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    networks: 
      - inception
    restart: always
#    healthcheck:
#      test: ["CMD-SHELL", "php -r 'exit(function_exists(\"curl_version\")?0:1);'"]
#      interval: 10s
#      timeout: 3s
#      retries: 10

  nginx:
    container_name: nginx
    image: nginx-inceprion
    build:
      context: ./requirements/nginx/
      args:
        - DEBIAN_TAG=${DEBIAN_TAG}
    depends_on:
      wordpress:
        condition: service_started
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    networks: 
      - inception
    ports:
      - "443:443"
    restart: always
