volumes:
  db_data:
    name: inception_db_data
  wp_data:
    name: inception_wp_data

networks:
  inception:
    name: inception
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    image: mariadb-inception
    build:
      context: ./requirements/mariadb/
      args:
        DEBIAN_TAG: ${DEBIAN_TAG}
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped
    ports:
      - "3306"
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -uroot -p$$MYSQL_ROOT_PASSWORD --socket=/var/run/mysqld/mysqld.sock"]
      interval: 10s
      timeout: 5s
      retries: 10

  wordpress:
    container_name: wordpress
    image: wordpress-inception
    build:
      context: ./requirements/wordpress/
      args:
        DEBIAN_TAG: ${DEBIAN_TAG}
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "php-fpm$$PHP_VERSION -t"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    container_name: nginx
    image: nginx-inception
    build:
      context: ./requirements/nginx/
      args:
        DEBIAN_TAG: ${DEBIAN_TAG}
    depends_on:
      wordpress:
        condition: service_started
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    ports:
      - "443:443"
    restart: unless-stopped
